# Generated by Django 2.2.24 on 2021-12-13 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twainlove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
